name: Solidity for the Nexss Programmer 2.x

on:
  push:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        os:
          [windows-latest, windows-2019, ubuntu-latest, macos-latest, macos-12]
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - run: npx @nexssp/cli file add myfile1.sol -f -t=helloWorld
      - run: npx @nexssp/cli myfile1.sol --asm
      - run: npx @nexssp/cli myfile1.sol --metadata
